#!/usr/bin/env ruby

require_relative "display"
require_relative "player"
require_relative "messages"
require_relative "game"

display = Display.new
player_one = HumanPlayer.new("Himalee", display)
player_two = ComputerPlayer.new("Computer", display)
messages = Messages.new
game = Game.new(player_one, player_two, display, messages)
game.play
