#!/usr/bin/env ruby

require_relative "session"

messages = Messages.new
move_validator = MoveValidator.new
display = Display.new(messages, move_validator)
session = Session.new(display)
session.start
