#!/usr/bin/env ruby

require_relative "display"
require_relative "player"
require_relative "messages"
require_relative "game"
require_relative "rules"
require_relative "console"

rules = Rules.new
console = Console.new
messages = Messages.new
display = Display.new(console, messages)
player_one = HumanPlayer.new("Himalee", console)
player_two = ComputerPlayer.new("Computer")
game = Game.new(player_one, player_two, display, rules)
game.play
